// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bot.proto

package stack_rpc_bot

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelpRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelpRequest) Reset()         { *m = HelpRequest{} }
func (m *HelpRequest) String() string { return proto.CompactTextString(m) }
func (*HelpRequest) ProtoMessage()    {}
func (*HelpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{0}
}

func (m *HelpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelpRequest.Unmarshal(m, b)
}
func (m *HelpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelpRequest.Marshal(b, m, deterministic)
}
func (m *HelpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelpRequest.Merge(m, src)
}
func (m *HelpRequest) XXX_Size() int {
	return xxx_messageInfo_HelpRequest.Size(m)
}
func (m *HelpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelpRequest proto.InternalMessageInfo

type HelpResponse struct {
	Usage                string   `protobuf:"bytes,1,opt,name=usage,proto3" json:"usage,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelpResponse) Reset()         { *m = HelpResponse{} }
func (m *HelpResponse) String() string { return proto.CompactTextString(m) }
func (*HelpResponse) ProtoMessage()    {}
func (*HelpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{1}
}

func (m *HelpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelpResponse.Unmarshal(m, b)
}
func (m *HelpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelpResponse.Marshal(b, m, deterministic)
}
func (m *HelpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelpResponse.Merge(m, src)
}
func (m *HelpResponse) XXX_Size() int {
	return xxx_messageInfo_HelpResponse.Size(m)
}
func (m *HelpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelpResponse proto.InternalMessageInfo

func (m *HelpResponse) GetUsage() string {
	if m != nil {
		return m.Usage
	}
	return ""
}

func (m *HelpResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type ExecRequest struct {
	Args                 []string `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecRequest) Reset()         { *m = ExecRequest{} }
func (m *ExecRequest) String() string { return proto.CompactTextString(m) }
func (*ExecRequest) ProtoMessage()    {}
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{2}
}

func (m *ExecRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecRequest.Unmarshal(m, b)
}
func (m *ExecRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecRequest.Marshal(b, m, deterministic)
}
func (m *ExecRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecRequest.Merge(m, src)
}
func (m *ExecRequest) XXX_Size() int {
	return xxx_messageInfo_ExecRequest.Size(m)
}
func (m *ExecRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecRequest proto.InternalMessageInfo

func (m *ExecRequest) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

type ExecResponse struct {
	Result               []byte   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecResponse) Reset()         { *m = ExecResponse{} }
func (m *ExecResponse) String() string { return proto.CompactTextString(m) }
func (*ExecResponse) ProtoMessage()    {}
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{3}
}

func (m *ExecResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecResponse.Unmarshal(m, b)
}
func (m *ExecResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecResponse.Marshal(b, m, deterministic)
}
func (m *ExecResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecResponse.Merge(m, src)
}
func (m *ExecResponse) XXX_Size() int {
	return xxx_messageInfo_ExecResponse.Size(m)
}
func (m *ExecResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecResponse proto.InternalMessageInfo

func (m *ExecResponse) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ExecResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*HelpRequest)(nil), "stack.rpc.bot.HelpRequest")
	proto.RegisterType((*HelpResponse)(nil), "stack.rpc.bot.HelpResponse")
	proto.RegisterType((*ExecRequest)(nil), "stack.rpc.bot.ExecRequest")
	proto.RegisterType((*ExecResponse)(nil), "stack.rpc.bot.ExecResponse")
}

func init() { proto.RegisterFile("bot.proto", fileDescriptor_51d7d70385167023) }

var fileDescriptor_51d7d70385167023 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x1b, 0x28, 0x45, 0xb9, 0xa4, 0x8b, 0x85, 0x50, 0x54, 0x96, 0xe0, 0xa9, 0x93, 0x07,
	0x58, 0x59, 0x10, 0x02, 0x31, 0xe7, 0x1b, 0x24, 0xe9, 0xa9, 0xaa, 0x68, 0x73, 0xe6, 0xce, 0x91,
	0xf8, 0x16, 0x7c, 0x65, 0xe4, 0x3f, 0x83, 0x51, 0xbb, 0xf9, 0xf9, 0x59, 0xef, 0xfd, 0x9e, 0xa1,
	0x1c, 0xc8, 0x19, 0xcb, 0xe4, 0x48, 0xad, 0xc5, 0xf5, 0xe3, 0x97, 0x61, 0x3b, 0x9a, 0x81, 0x9c,
	0x5e, 0x43, 0xf5, 0x89, 0x47, 0xdb, 0xe1, 0xf7, 0x8c, 0xe2, 0xf4, 0x07, 0xd4, 0x51, 0x8a, 0xa5,
	0x49, 0x50, 0xdd, 0xc1, 0xcd, 0x2c, 0xfd, 0x1e, 0x9b, 0xa2, 0x2d, 0xb6, 0x65, 0x17, 0x85, 0x6a,
	0xa1, 0xda, 0xa1, 0x8c, 0x7c, 0xb0, 0xee, 0x40, 0x53, 0x73, 0x15, 0xbc, 0xfc, 0x4a, 0x3f, 0x42,
	0xf5, 0xfe, 0x83, 0x63, 0x8a, 0x55, 0x0a, 0x96, 0x3d, 0xef, 0xa5, 0x29, 0xda, 0xeb, 0x6d, 0xd9,
	0x85, 0xb3, 0x7e, 0x81, 0x3a, 0x3e, 0x49, 0x55, 0xf7, 0xb0, 0x62, 0x94, 0xf9, 0xe8, 0x42, 0x57,
	0xdd, 0x25, 0xe5, 0x11, 0x90, 0x99, 0x38, 0xd5, 0x44, 0xf1, 0xf4, 0x5b, 0xc0, 0xed, 0x1b, 0x9d,
	0x4e, 0xfd, 0xb4, 0x53, 0xaf, 0xb0, 0xf4, 0xd0, 0x6a, 0x63, 0xfe, 0x6d, 0x33, 0xd9, 0xb0, 0xcd,
	0xc3, 0x45, 0x2f, 0x56, 0xeb, 0x85, 0x8f, 0xf0, 0x30, 0x67, 0x11, 0xd9, 0x88, 0xb3, 0x88, 0x9c,
	0x5e, 0x2f, 0x86, 0x55, 0xf8, 0xdf, 0xe7, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb5, 0xcb, 0xc9,
	0x68, 0x6c, 0x01, 0x00, 0x00,
}
