// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client.proto

package stack_rpc_client

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Endpoint             string   `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	ContentType          string   `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Body                 []byte   `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Request) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *Request) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *Request) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type Response struct {
	Body                 []byte   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type Message struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	ContentType          string   `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Body                 []byte   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{2}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Message) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *Message) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "stack.rpc.client.Request")
	proto.RegisterType((*Response)(nil), "stack.rpc.client.Response")
	proto.RegisterType((*Message)(nil), "stack.rpc.client.Message")
}

func init() { proto.RegisterFile("client.proto", fileDescriptor_014de31d7ac8c57c) }

var fileDescriptor_014de31d7ac8c57c = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x41, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0xbb, 0x6d, 0xfe, 0x49, 0xff, 0x63, 0x0e, 0x32, 0x78, 0x88, 0x39, 0x48, 0xcd, 0x29,
	0xa7, 0x45, 0xf4, 0x03, 0x88, 0x14, 0x8f, 0x82, 0x44, 0xf1, 0x2a, 0xc9, 0x76, 0xd0, 0xc5, 0xb8,
	0xbb, 0x66, 0xa7, 0x85, 0x7c, 0x4e, 0xbf, 0x90, 0xb0, 0x89, 0x56, 0xb4, 0xbd, 0x78, 0xdb, 0x37,
	0x3f, 0x78, 0xf3, 0xf6, 0x0d, 0xa4, 0xaa, 0xd5, 0x64, 0x58, 0xba, 0xce, 0xb2, 0xc5, 0x43, 0xcf,
	0xb5, 0x7a, 0x91, 0x9d, 0x53, 0x72, 0x98, 0x17, 0x1b, 0x48, 0x2a, 0x7a, 0x5b, 0x93, 0x67, 0xcc,
	0x20, 0xf1, 0xd4, 0x6d, 0xb4, 0xa2, 0x4c, 0x2c, 0x44, 0xf9, 0xbf, 0xfa, 0x94, 0x98, 0xc3, 0x9c,
	0xcc, 0xca, 0x59, 0x6d, 0x38, 0x9b, 0x06, 0xf4, 0xa5, 0xf1, 0x14, 0x52, 0x65, 0x0d, 0x93, 0xe1,
	0x47, 0xee, 0x1d, 0x65, 0xb3, 0xc0, 0x0f, 0xc6, 0xd9, 0x7d, 0xef, 0x08, 0x11, 0xa2, 0xc6, 0xae,
	0xfa, 0x2c, 0x5a, 0x88, 0x32, 0xad, 0xc2, 0xbb, 0x38, 0x81, 0x79, 0x45, 0xde, 0x59, 0xe3, 0xb7,
	0x5c, 0x7c, 0xe3, 0x0f, 0x90, 0xdc, 0x90, 0xf7, 0xf5, 0x13, 0xe1, 0x11, 0xfc, 0x63, 0xeb, 0xb4,
	0x1a, 0x53, 0x0d, 0xe2, 0xd7, 0xde, 0xe9, 0xfe, 0xbd, 0xb3, 0xad, 0xef, 0xf9, 0xbb, 0x80, 0x78,
	0x19, 0xbe, 0x8e, 0x97, 0x10, 0x2d, 0xeb, 0xb6, 0xc5, 0x63, 0xf9, 0xb3, 0x15, 0x39, 0x56, 0x92,
	0xe7, 0xbb, 0xd0, 0x90, 0xba, 0x98, 0xe0, 0x35, 0xc4, 0x77, 0xdc, 0x51, 0xfd, 0xfa, 0x67, 0x8b,
	0x52, 0x9c, 0x09, 0xbc, 0x82, 0xe4, 0x76, 0xdd, 0xb4, 0xda, 0x3f, 0xef, 0xf2, 0x19, 0x5b, 0xc8,
	0xf7, 0xa3, 0x62, 0xd2, 0xc4, 0xe1, 0xbc, 0x17, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x82, 0xa8,
	0x04, 0x0c, 0xee, 0x01, 0x00, 0x00,
}
