// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

package stack_rpc_server

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HandleRequest struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Endpoint             string   `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Protocol             string   `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleRequest) Reset()         { *m = HandleRequest{} }
func (m *HandleRequest) String() string { return proto.CompactTextString(m) }
func (*HandleRequest) ProtoMessage()    {}
func (*HandleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{0}
}

func (m *HandleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleRequest.Unmarshal(m, b)
}
func (m *HandleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleRequest.Marshal(b, m, deterministic)
}
func (m *HandleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleRequest.Merge(m, src)
}
func (m *HandleRequest) XXX_Size() int {
	return xxx_messageInfo_HandleRequest.Size(m)
}
func (m *HandleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandleRequest proto.InternalMessageInfo

func (m *HandleRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *HandleRequest) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *HandleRequest) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

type HandleResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleResponse) Reset()         { *m = HandleResponse{} }
func (m *HandleResponse) String() string { return proto.CompactTextString(m) }
func (*HandleResponse) ProtoMessage()    {}
func (*HandleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{1}
}

func (m *HandleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleResponse.Unmarshal(m, b)
}
func (m *HandleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleResponse.Marshal(b, m, deterministic)
}
func (m *HandleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleResponse.Merge(m, src)
}
func (m *HandleResponse) XXX_Size() int {
	return xxx_messageInfo_HandleResponse.Size(m)
}
func (m *HandleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandleResponse proto.InternalMessageInfo

type SubscribeRequest struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeRequest) Reset()         { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()    {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{2}
}

func (m *SubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeRequest.Unmarshal(m, b)
}
func (m *SubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeRequest.Merge(m, src)
}
func (m *SubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeRequest.Size(m)
}
func (m *SubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeRequest proto.InternalMessageInfo

func (m *SubscribeRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type SubscribeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeResponse) Reset()         { *m = SubscribeResponse{} }
func (m *SubscribeResponse) String() string { return proto.CompactTextString(m) }
func (*SubscribeResponse) ProtoMessage()    {}
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{3}
}

func (m *SubscribeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeResponse.Unmarshal(m, b)
}
func (m *SubscribeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeResponse.Marshal(b, m, deterministic)
}
func (m *SubscribeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeResponse.Merge(m, src)
}
func (m *SubscribeResponse) XXX_Size() int {
	return xxx_messageInfo_SubscribeResponse.Size(m)
}
func (m *SubscribeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*HandleRequest)(nil), "stack.rpc.server.HandleRequest")
	proto.RegisterType((*HandleResponse)(nil), "stack.rpc.server.HandleResponse")
	proto.RegisterType((*SubscribeRequest)(nil), "stack.rpc.server.SubscribeRequest")
	proto.RegisterType((*SubscribeResponse)(nil), "stack.rpc.server.SubscribeResponse")
}

func init() { proto.RegisterFile("server.proto", fileDescriptor_ad098daeda4239f7) }

var fileDescriptor_ad098daeda4239f7 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xb1, 0x4e, 0x86, 0x30,
	0x14, 0x85, 0x45, 0x23, 0xca, 0x8d, 0x1a, 0xac, 0x0e, 0x0d, 0x8b, 0xa4, 0x2e, 0x4c, 0x1d, 0xf4,
	0x25, 0x5c, 0x5c, 0x20, 0x71, 0x87, 0x72, 0x87, 0x46, 0xd2, 0xd6, 0xb6, 0xf8, 0x5a, 0xbe, 0xa2,
	0xa1, 0xa5, 0x44, 0xf9, 0xf3, 0xff, 0xe3, 0xe9, 0x39, 0xf7, 0x7e, 0xe7, 0x16, 0x6e, 0x1c, 0xda,
	0x6f, 0xb4, 0xdc, 0x58, 0xed, 0x35, 0x29, 0x9d, 0xef, 0xc5, 0x27, 0xb7, 0x46, 0xf0, 0xf8, 0xce,
	0x7a, 0xb8, 0x7d, 0xeb, 0xd5, 0x38, 0x61, 0x8b, 0x5f, 0x33, 0x3a, 0x4f, 0x28, 0x5c, 0x2d, 0x96,
	0x14, 0x48, 0xb3, 0x3a, 0x6b, 0x8a, 0x36, 0x49, 0x52, 0xc1, 0x35, 0xaa, 0xd1, 0x68, 0xa9, 0x3c,
	0x3d, 0x0f, 0xd6, 0xa6, 0x17, 0x2f, 0x10, 0x84, 0x9e, 0xe8, 0x45, 0xf4, 0x92, 0x66, 0x25, 0xdc,
	0x25, 0x84, 0x33, 0x5a, 0x39, 0x64, 0x0d, 0x94, 0xdd, 0x3c, 0x38, 0x61, 0xe5, 0xb0, 0x71, 0x1f,
	0xe1, 0xd2, 0x6b, 0x23, 0xc5, 0x4a, 0x8d, 0x82, 0x3d, 0xc0, 0xfd, 0x9f, 0x64, 0x1c, 0x7f, 0xf9,
	0xc9, 0x20, 0xef, 0x42, 0x7d, 0xf2, 0x0e, 0x79, 0xdc, 0x4d, 0x9e, 0xf8, 0xfe, 0x36, 0xfe, 0xef,
	0xb0, 0xaa, 0x3e, 0x1e, 0x58, 0x6b, 0x9d, 0x91, 0x0f, 0x28, 0x36, 0x1c, 0x61, 0x87, 0x03, 0xfb,
	0xd6, 0xd5, 0xf3, 0xc9, 0x4c, 0xda, 0x3b, 0xe4, 0xe1, 0x33, 0x5e, 0x7f, 0x03, 0x00, 0x00, 0xff,
	0xff, 0xb8, 0xfc, 0xa6, 0x40, 0x8e, 0x01, 0x00, 0x00,
}
