// Code generated by protoc-gen-stack. DO NOT EDIT.
// source: github.com/stack-labs/stack-rpc-plugins/service/stackway/test/proto/test.proto

package stack_rpc_stackway_test

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	proto1 "github.com/stack-labs/stack-rpc/api/proto"
	math "math"
)

import (
	context "context"
	api "github.com/stack-labs/stack-rpc/api"
	client "github.com/stack-labs/stack-rpc/client"
	server "github.com/stack-labs/stack-rpc/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Test service

func NewTestEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Test service

type TestService interface {
	// rpc handler
	Rpc(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// api handler
	Api(ctx context.Context, in *proto1.Request, opts ...client.CallOption) (*proto1.Response, error)
}

type testService struct {
	c    client.Client
	name string
}

func NewTestService(name string, c client.Client) TestService {
	return &testService{
		c:    c,
		name: name,
	}
}

func (c *testService) Rpc(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Test.Rpc", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testService) Api(ctx context.Context, in *proto1.Request, opts ...client.CallOption) (*proto1.Response, error) {
	req := c.c.NewRequest(c.name, "Test.Api", in)
	out := new(proto1.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Test service

type TestHandler interface {
	// rpc handler
	Rpc(context.Context, *Request, *Response) error
	// api handler
	Api(context.Context, *proto1.Request, *proto1.Response) error
}

func RegisterTestHandler(s server.Server, hdlr TestHandler, opts ...server.HandlerOption) error {
	type test interface {
		Rpc(ctx context.Context, in *Request, out *Response) error
		Api(ctx context.Context, in *proto1.Request, out *proto1.Response) error
	}
	type Test struct {
		test
	}
	h := &testHandler{hdlr}
	return s.Handle(s.NewHandler(&Test{h}, opts...))
}

type testHandler struct {
	TestHandler
}

func (h *testHandler) Rpc(ctx context.Context, in *Request, out *Response) error {
	return h.TestHandler.Rpc(ctx, in, out)
}

func (h *testHandler) Api(ctx context.Context, in *proto1.Request, out *proto1.Response) error {
	return h.TestHandler.Api(ctx, in, out)
}
